# Generated by Django 4.2.7 on 2024-01-04 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
