# Generated by Django 4.2.7 on 2024-01-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_expense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzaction',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
