# Generated by Django 4.2.6 on 2023-12-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
